<?php
/**
 * The Blink HTMLTokenizer ported to PHP.
 *
 * Copyright (C) 2008 Apple Inc. All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

namespace zz\Html;

class HTMLNames {

    // Tags
    const aTag = 'a';
    const abbrTag = 'abbr';
    const acronymTag = 'acronym';
    const addressTag = 'address';
    const appletTag = 'applet';
    const areaTag = 'area';
    const articleTag = 'article';
    const asideTag = 'aside';
    const audioTag = 'audio';
    const bTag = 'b';
    const baseTag = 'base';
    const basefontTag = 'basefont';
    const bdoTag = 'bdo';
    const bgsoundTag = 'bgsound';
    const bigTag = 'big';
    const blockquoteTag = 'blockquote';
    const bodyTag = 'body';
    const brTag = 'br';
    const buttonTag = 'button';
    const canvasTag = 'canvas';
    const captionTag = 'caption';
    const centerTag = 'center';
    const citeTag = 'cite';
    const codeTag = 'code';
    const colTag = 'col';
    const colgroupTag = 'colgroup';
    const commandTag = 'command';
    const datalistTag = 'datalist';
    const ddTag = 'dd';
    const delTag = 'del';
    const detailsTag = 'details';
    const dfnTag = 'dfn';
    const dirTag = 'dir';
    const divTag = 'div';
    const dlTag = 'dl';
    const dtTag = 'dt';
    const emTag = 'em';
    const embedTag = 'embed';
    const fieldsetTag = 'fieldset';
    const figcaptionTag = 'figcaption';
    const figureTag = 'figure';
    const fontTag = 'font';
    const footerTag = 'footer';
    const formTag = 'form';
    const frameTag = 'frame';
    const framesetTag = 'frameset';
    const h1Tag = 'h1';
    const h2Tag = 'h2';
    const h3Tag = 'h3';
    const h4Tag = 'h4';
    const h5Tag = 'h5';
    const h6Tag = 'h6';
    const headTag = 'head';
    const headerTag = 'header';
    const hgroupTag = 'hgroup';
    const hrTag = 'hr';
    const htmlTag = 'html';
    const iTag = 'i';
    const iframeTag = 'iframe';
    const imageTag = 'image';
    const imgTag = 'img';
    const inputTag = 'input';
    const insTag = 'ins';
    const isindexTag = 'isindex';
    const kbdTag = 'kbd';
    const keygenTag = 'keygen';
    const labelTag = 'label';
    const layerTag = 'layer';
    const legendTag = 'legend';
    const liTag = 'li';
    const linkTag = 'link';
    const listingTag = 'listing';
    const mapTag = 'map';
    const markTag = 'mark';
    const marqueeTag = 'marquee';
    const menuTag = 'menu';
    const metaTag = 'meta';
    const meterTag = 'meter';
    const navTag = 'nav';
    const nobrTag = 'nobr';
    const noembedTag = 'noembed';
    const noframesTag = 'noframes';
    const nolayerTag = 'nolayer';
    const noscriptTag = 'noscript';
    const objectTag = 'object';
    const olTag = 'ol';
    const optgroupTag = 'optgroup';
    const optionTag = 'option';
    const outputTag = 'output';
    const pTag = 'p';
    const paramTag = 'param';
    const plaintextTag = 'plaintext';
    const preTag = 'pre';
    const progressTag = 'progress';
    const qTag = 'q';
    const rpTag = 'rp';
    const rtTag = 'rt';
    const rubyTag = 'ruby';
    const sTag = 's';
    const sampTag = 'samp';
    const scriptTag = 'script';
    const sectionTag = 'section';
    const selectTag = 'select';
    const smallTag = 'small';
    const sourceTag = 'source';
    const spanTag = 'span';
    const strikeTag = 'strike';
    const strongTag = 'strong';
    const styleTag = 'style';
    const subTag = 'sub';
    const summaryTag = 'summary';
    const supTag = 'sup';
    const tableTag = 'table';
    const tbodyTag = 'tbody';
    const tdTag = 'td';
    const textareaTag = 'textarea';
    const tfootTag = 'tfoot';
    const thTag = 'th';
    const theadTag = 'thead';
    const titleTag = 'title';
    const trTag = 'tr';
    const trackTag = 'track';
    const ttTag = 'tt';
    const uTag = 'u';
    const ulTag = 'ul';
    const varTag = 'var';
    const videoTag = 'video';
    const wbrTag = 'wbr';
    const xmpTag = 'xmp';

    // Attributes
    const abbrAttr = 'abbr';
    const acceptAttr = 'accept';
    const accept_charsetAttr = 'accept-charset';
    const accesskeyAttr = 'accesskey';
    const actionAttr = 'action';
    const alignAttr = 'align';
    const alinkAttr = 'alink';
    const altAttr = 'alt';
    const archiveAttr = 'archive';
    const aria_activedescendantAttr = 'aria-activedescendant';
    const aria_atomicAttr = 'aria-atomic';
    const aria_busyAttr = 'aria-busy';
    const aria_checkedAttr = 'aria-checked';
    const aria_controlsAttr = 'aria-controls';
    const aria_describedbyAttr = 'aria-describedby';
    const aria_disabledAttr = 'aria-disabled';
    const aria_dropeffectAttr = 'aria-dropeffect';
    const aria_expandedAttr = 'aria-expanded';
    const aria_flowtoAttr = 'aria-flowto';
    const aria_grabbedAttr = 'aria-grabbed';
    const aria_haspopupAttr = 'aria-haspopup';
    const aria_helpAttr = 'aria-help';
    const aria_hiddenAttr = 'aria-hidden';
    const aria_invalidAttr = 'aria-invalid';
    const aria_labelAttr = 'aria-label';
    const aria_labeledbyAttr = 'aria-labeledby';
    const aria_labelledbyAttr = 'aria-labelledby';
    const aria_levelAttr = 'aria-level';
    const aria_liveAttr = 'aria-live';
    const aria_multilineAttr = 'aria-multiline';
    const aria_multiselectableAttr = 'aria-multiselectable';
    const aria_orientationAttr = 'aria-orientation';
    const aria_ownsAttr = 'aria-owns';
    const aria_pressedAttr = 'aria-pressed';
    const aria_readonlyAttr = 'aria-readonly';
    const aria_relevantAttr = 'aria-relevant';
    const aria_requiredAttr = 'aria-required';
    const aria_selectedAttr = 'aria-selected';
    const aria_sortAttr = 'aria-sort';
    const aria_valuemaxAttr = 'aria-valuemax';
    const aria_valueminAttr = 'aria-valuemin';
    const aria_valuenowAttr = 'aria-valuenow';
    const aria_valuetextAttr = 'aria-valuetext';
    const asyncAttr = 'async';
    const autocompleteAttr = 'autocomplete';
    const autofocusAttr = 'autofocus';
    const autoplayAttr = 'autoplay';
    const autosaveAttr = 'autosave';
    const axisAttr = 'axis';
    const backgroundAttr = 'background';
    const behaviorAttr = 'behavior';
    const bgcolorAttr = 'bgcolor';
    const bgpropertiesAttr = 'bgproperties';
    const borderAttr = 'border';
    const bordercolorAttr = 'bordercolor';
    const cellborderAttr = 'cellborder';
    const cellpaddingAttr = 'cellpadding';
    const cellspacingAttr = 'cellspacing';
    const challengeAttr = 'challenge';
    const charAttr = 'char';
    const charoffAttr = 'charoff';
    const charsetAttr = 'charset';
    const checkedAttr = 'checked';
    const citeAttr = 'cite';
    const classAttr = 'class';
    const classidAttr = 'classid';
    const clearAttr = 'clear';
    const codeAttr = 'code';
    const codebaseAttr = 'codebase';
    const codetypeAttr = 'codetype';
    const colorAttr = 'color';
    const colsAttr = 'cols';
    const colspanAttr = 'colspan';
    const compactAttr = 'compact';
    const compositeAttr = 'composite';
    const contentAttr = 'content';
    const contenteditableAttr = 'contenteditable';
    const controlsAttr = 'controls';
    const coordsAttr = 'coords';
    const dataAttr = 'data';
    const datetimeAttr = 'datetime';
    const declareAttr = 'declare';
    const defaultAttr = 'default';
    const deferAttr = 'defer';
    const dirAttr = 'dir';
    const directionAttr = 'direction';
    const disabledAttr = 'disabled';
    const draggableAttr = 'draggable';
    const enctypeAttr = 'enctype';
    const endAttr = 'end';
    const eventAttr = 'event';
    const expandedAttr = 'expanded';
    const faceAttr = 'face';
    const focusedAttr = 'focused';
    const forAttr = 'for';
    const formAttr = 'form';
    const formactionAttr = 'formaction';
    const formenctypeAttr = 'formenctype';
    const formmethodAttr = 'formmethod';
    const formnovalidateAttr = 'formnovalidate';
    const formtargetAttr = 'formtarget';
    const frameAttr = 'frame';
    const frameborderAttr = 'frameborder';
    const headersAttr = 'headers';
    const heightAttr = 'height';
    const hiddenAttr = 'hidden';
    const highAttr = 'high';
    const hrefAttr = 'href';
    const hreflangAttr = 'hreflang';
    const hspaceAttr = 'hspace';
    const http_equivAttr = 'http-equiv';
    const idAttr = 'id';
    const incrementalAttr = 'incremental';
    const indeterminateAttr = 'indeterminate';
    const ismapAttr = 'ismap';
    const keytypeAttr = 'keytype';
    const kindAttr = 'kind';
    const labelAttr = 'label';
    const langAttr = 'lang';
    const languageAttr = 'language';
    const leftmarginAttr = 'leftmargin';
    const linkAttr = 'link';
    const listAttr = 'list';
    const longdescAttr = 'longdesc';
    const loopAttr = 'loop';
    const loopendAttr = 'loopend';
    const loopstartAttr = 'loopstart';
    const lowAttr = 'low';
    const lowsrcAttr = 'lowsrc';
    const manifestAttr = 'manifest';
    const marginheightAttr = 'marginheight';
    const marginwidthAttr = 'marginwidth';
    const maxAttr = 'max';
    const maxlengthAttr = 'maxlength';
    const mayscriptAttr = 'mayscript';
    const mediaAttr = 'media';
    const methodAttr = 'method';
    const minAttr = 'min';
    const multipleAttr = 'multiple';
    const nameAttr = 'name';
    const nohrefAttr = 'nohref';
    const noresizeAttr = 'noresize';
    const noshadeAttr = 'noshade';
    const novalidateAttr = 'novalidate';
    const nowrapAttr = 'nowrap';
    const objectAttr = 'object';
    const onabortAttr = 'onabort';
    const onbeforecopyAttr = 'onbeforecopy';
    const onbeforecutAttr = 'onbeforecut';
    const onbeforeloadAttr = 'onbeforeload';
    const onbeforepasteAttr = 'onbeforepaste';
    const onbeforeprocessAttr = 'onbeforeprocess';
    const onbeforeunloadAttr = 'onbeforeunload';
    const onblurAttr = 'onblur';
    const oncanplayAttr = 'oncanplay';
    const oncanplaythroughAttr = 'oncanplaythrough';
    const onchangeAttr = 'onchange';
    const onclickAttr = 'onclick';
    const oncontextmenuAttr = 'oncontextmenu';
    const oncopyAttr = 'oncopy';
    const oncutAttr = 'oncut';
    const ondblclickAttr = 'ondblclick';
    const ondragAttr = 'ondrag';
    const ondragendAttr = 'ondragend';
    const ondragenterAttr = 'ondragenter';
    const ondragleaveAttr = 'ondragleave';
    const ondragoverAttr = 'ondragover';
    const ondragstartAttr = 'ondragstart';
    const ondropAttr = 'ondrop';
    const ondurationchangeAttr = 'ondurationchange';
    const onemptiedAttr = 'onemptied';
    const onendedAttr = 'onended';
    const onerrorAttr = 'onerror';
    const onfocusAttr = 'onfocus';
    const onfocusinAttr = 'onfocusin';
    const onfocusoutAttr = 'onfocusout';
    const onhashchangeAttr = 'onhashchange';
    const oninputAttr = 'oninput';
    const oninvalidAttr = 'oninvalid';
    const onkeydownAttr = 'onkeydown';
    const onkeypressAttr = 'onkeypress';
    const onkeyupAttr = 'onkeyup';
    const onloadAttr = 'onload';
    const onloadeddataAttr = 'onloadeddata';
    const onloadedmetadataAttr = 'onloadedmetadata';
    const onloadstartAttr = 'onloadstart';
    const onmousedownAttr = 'onmousedown';
    const onmousemoveAttr = 'onmousemove';
    const onmouseoutAttr = 'onmouseout';
    const onmouseoverAttr = 'onmouseover';
    const onmouseupAttr = 'onmouseup';
    const onmousewheelAttr = 'onmousewheel';
    const onofflineAttr = 'onoffline';
    const ononlineAttr = 'ononline';
    const onorientationchangeAttr = 'onorientationchange';
    const onpagehideAttr = 'onpagehide';
    const onpageshowAttr = 'onpageshow';
    const onpasteAttr = 'onpaste';
    const onpauseAttr = 'onpause';
    const onplayAttr = 'onplay';
    const onplayingAttr = 'onplaying';
    const onpopstateAttr = 'onpopstate';
    const onprogressAttr = 'onprogress';
    const onratechangeAttr = 'onratechange';
    const onresetAttr = 'onreset';
    const onresizeAttr = 'onresize';
    const onscrollAttr = 'onscroll';
    const onsearchAttr = 'onsearch';
    const onseekedAttr = 'onseeked';
    const onseekingAttr = 'onseeking';
    const onselectAttr = 'onselect';
    const onselectionchangeAttr = 'onselectionchange';
    const onselectstartAttr = 'onselectstart';
    const onstalledAttr = 'onstalled';
    const onstorageAttr = 'onstorage';
    const onsubmitAttr = 'onsubmit';
    const onsuspendAttr = 'onsuspend';
    const ontimeupdateAttr = 'ontimeupdate';
    const ontouchcancelAttr = 'ontouchcancel';
    const ontouchendAttr = 'ontouchend';
    const ontouchmoveAttr = 'ontouchmove';
    const ontouchstartAttr = 'ontouchstart';
    const onunloadAttr = 'onunload';
    const onvolumechangeAttr = 'onvolumechange';
    const onwaitingAttr = 'onwaiting';
    const onwebkitanimationendAttr = 'onwebkitanimationend';
    const onwebkitanimationiterationAttr = 'onwebkitanimationiteration';
    const onwebkitanimationstartAttr = 'onwebkitanimationstart';
    const onwebkitbeginfullscreenAttr = 'onwebkitbeginfullscreen';
    const onwebkitendfullscreenAttr = 'onwebkitendfullscreen';
    const onwebkitfullscreenchangeAttr = 'onwebkitfullscreenchange';
    const onwebkitspeechchangeAttr = 'onwebkitspeechchange';
    const onwebkittransitionendAttr = 'onwebkittransitionend';
    const openAttr = 'open';
    const optimumAttr = 'optimum';
    const patternAttr = 'pattern';
    const pingAttr = 'ping';
    const placeholderAttr = 'placeholder';
    const playcountAttr = 'playcount';
    const pluginspageAttr = 'pluginspage';
    const pluginurlAttr = 'pluginurl';
    const posterAttr = 'poster';
    const precisionAttr = 'precision';
    const preloadAttr = 'preload';
    const primaryAttr = 'primary';
    const profileAttr = 'profile';
    const progressAttr = 'progress';
    const promptAttr = 'prompt';
    const readonlyAttr = 'readonly';
    const relAttr = 'rel';
    const requiredAttr = 'required';
    const resultsAttr = 'results';
    const revAttr = 'rev';
    const roleAttr = 'role';
    const rowsAttr = 'rows';
    const rowspanAttr = 'rowspan';
    const rulesAttr = 'rules';
    const sandboxAttr = 'sandbox';
    const schemeAttr = 'scheme';
    const scopeAttr = 'scope';
    const scrollamountAttr = 'scrollamount';
    const scrolldelayAttr = 'scrolldelay';
    const scrollingAttr = 'scrolling';
    const selectedAttr = 'selected';
    const shapeAttr = 'shape';
    const sizeAttr = 'size';
    const sortableAttr = 'sortable';
    const sortdirectionAttr = 'sortdirection';
    const spanAttr = 'span';
    const spellcheckAttr = 'spellcheck';
    const srcAttr = 'src';
    const srclangAttr = 'srclang';
    const standbyAttr = 'standby';
    const startAttr = 'start';
    const stepAttr = 'step';
    const styleAttr = 'style';
    const summaryAttr = 'summary';
    const tabindexAttr = 'tabindex';
    const tableborderAttr = 'tableborder';
    const targetAttr = 'target';
    const textAttr = 'text';
    const titleAttr = 'title';
    const topAttr = 'top';
    const topmarginAttr = 'topmargin';
    const truespeedAttr = 'truespeed';
    const typeAttr = 'type';
    const usemapAttr = 'usemap';
    const valignAttr = 'valign';
    const valueAttr = 'value';
    const valuetypeAttr = 'valuetype';
    const versionAttr = 'version';
    const viewsourceAttr = 'viewsource';
    const vlinkAttr = 'vlink';
    const vspaceAttr = 'vspace';
    const webkitallowfullscreenAttr = 'webkitallowfullscreen';
    const webkitdirectoryAttr = 'webkitdirectory';
    const webkitgrammarAttr = 'x-webkit-grammar';
    const webkitspeechAttr = 'x-webkit-speech';
    const widthAttr = 'width';
    const wrapAttr = 'wrap';

    public static function getHTMLTags() {
        return array(
            static::aTag => static::aTag,
            static::abbrTag => static::abbrTag,
            static::acronymTag => static::acronymTag,
            static::addressTag => static::addressTag,
            static::appletTag => static::appletTag,
            static::areaTag => static::areaTag,
            static::articleTag => static::articleTag,
            static::asideTag => static::asideTag,
            static::audioTag => static::audioTag,
            static::bTag => static::bTag,
            static::baseTag => static::baseTag,
            static::basefontTag => static::basefontTag,
            static::bdoTag => static::bdoTag,
            static::bgsoundTag => static::bgsoundTag,
            static::bigTag => static::bigTag,
            static::blockquoteTag => static::blockquoteTag,
            static::bodyTag => static::bodyTag,
            static::brTag => static::brTag,
            static::buttonTag => static::buttonTag,
            static::canvasTag => static::canvasTag,
            static::captionTag => static::captionTag,
            static::centerTag => static::centerTag,
            static::citeTag => static::citeTag,
            static::codeTag => static::codeTag,
            static::colTag => static::colTag,
            static::colgroupTag => static::colgroupTag,
            static::commandTag => static::commandTag,
            static::datalistTag => static::datalistTag,
            static::ddTag => static::ddTag,
            static::delTag => static::delTag,
            static::detailsTag => static::detailsTag,
            static::dfnTag => static::dfnTag,
            static::dirTag => static::dirTag,
            static::divTag => static::divTag,
            static::dlTag => static::dlTag,
            static::dtTag => static::dtTag,
            static::emTag => static::emTag,
            static::embedTag => static::embedTag,
            static::fieldsetTag => static::fieldsetTag,
            static::figcaptionTag => static::figcaptionTag,
            static::figureTag => static::figureTag,
            static::fontTag => static::fontTag,
            static::footerTag => static::footerTag,
            static::formTag => static::formTag,
            static::frameTag => static::frameTag,
            static::framesetTag => static::framesetTag,
            static::h1Tag => static::h1Tag,
            static::h2Tag => static::h2Tag,
            static::h3Tag => static::h3Tag,
            static::h4Tag => static::h4Tag,
            static::h5Tag => static::h5Tag,
            static::h6Tag => static::h6Tag,
            static::headTag => static::headTag,
            static::headerTag => static::headerTag,
            static::hgroupTag => static::hgroupTag,
            static::hrTag => static::hrTag,
            static::htmlTag => static::htmlTag,
            static::iTag => static::iTag,
            static::iframeTag => static::iframeTag,
            static::imageTag => static::imageTag,
            static::imgTag => static::imgTag,
            static::inputTag => static::inputTag,
            static::insTag => static::insTag,
            static::isindexTag => static::isindexTag,
            static::kbdTag => static::kbdTag,
            static::keygenTag => static::keygenTag,
            static::labelTag => static::labelTag,
            static::layerTag => static::layerTag,
            static::legendTag => static::legendTag,
            static::liTag => static::liTag,
            static::linkTag => static::linkTag,
            static::listingTag => static::listingTag,
            static::mapTag => static::mapTag,
            static::markTag => static::markTag,
            static::marqueeTag => static::marqueeTag,
            static::menuTag => static::menuTag,
            static::metaTag => static::metaTag,
            static::meterTag => static::meterTag,
            static::navTag => static::navTag,
            static::nobrTag => static::nobrTag,
            static::noembedTag => static::noembedTag,
            static::noframesTag => static::noframesTag,
            static::nolayerTag => static::nolayerTag,
            static::noscriptTag => static::noscriptTag,
            static::objectTag => static::objectTag,
            static::olTag => static::olTag,
            static::optgroupTag => static::optgroupTag,
            static::optionTag => static::optionTag,
            static::outputTag => static::outputTag,
            static::pTag => static::pTag,
            static::paramTag => static::paramTag,
            static::plaintextTag => static::plaintextTag,
            static::preTag => static::preTag,
            static::progressTag => static::progressTag,
            static::qTag => static::qTag,
            static::rpTag => static::rpTag,
            static::rtTag => static::rtTag,
            static::rubyTag => static::rubyTag,
            static::sTag => static::sTag,
            static::sampTag => static::sampTag,
            static::scriptTag => static::scriptTag,
            static::sectionTag => static::sectionTag,
            static::selectTag => static::selectTag,
            static::smallTag => static::smallTag,
            static::sourceTag => static::sourceTag,
            static::spanTag => static::spanTag,
            static::strikeTag => static::strikeTag,
            static::strongTag => static::strongTag,
            static::styleTag => static::styleTag,
            static::subTag => static::subTag,
            static::summaryTag => static::summaryTag,
            static::supTag => static::supTag,
            static::tableTag => static::tableTag,
            static::tbodyTag => static::tbodyTag,
            static::tdTag => static::tdTag,
            static::textareaTag => static::textareaTag,
            static::tfootTag => static::tfootTag,
            static::thTag => static::thTag,
            static::theadTag => static::theadTag,
            static::titleTag => static::titleTag,
            static::trTag => static::trTag,
            static::trackTag => static::trackTag,
            static::ttTag => static::ttTag,
            static::uTag => static::uTag,
            static::ulTag => static::ulTag,
            static::varTag => static::varTag,
            static::videoTag => static::videoTag,
            static::wbrTag => static::wbrTag,
            static::xmpTag => static::xmpTag,
        );
    }

    public static function getHTMLAttrs() {
        return array(
            static::abbrAttr => static::abbrAttr,
            static::acceptAttr => static::acceptAttr,
            static::accept_charsetAttr => static::accept_charsetAttr,
            static::accesskeyAttr => static::accesskeyAttr,
            static::actionAttr => static::actionAttr,
            static::alignAttr => static::alignAttr,
            static::alinkAttr => static::alinkAttr,
            static::altAttr => static::altAttr,
            static::archiveAttr => static::archiveAttr,
            static::aria_activedescendantAttr => static::aria_activedescendantAttr,
            static::aria_atomicAttr => static::aria_atomicAttr,
            static::aria_busyAttr => static::aria_busyAttr,
            static::aria_checkedAttr => static::aria_checkedAttr,
            static::aria_controlsAttr => static::aria_controlsAttr,
            static::aria_describedbyAttr => static::aria_describedbyAttr,
            static::aria_disabledAttr => static::aria_disabledAttr,
            static::aria_dropeffectAttr => static::aria_dropeffectAttr,
            static::aria_expandedAttr => static::aria_expandedAttr,
            static::aria_flowtoAttr => static::aria_flowtoAttr,
            static::aria_grabbedAttr => static::aria_grabbedAttr,
            static::aria_haspopupAttr => static::aria_haspopupAttr,
            static::aria_helpAttr => static::aria_helpAttr,
            static::aria_hiddenAttr => static::aria_hiddenAttr,
            static::aria_invalidAttr => static::aria_invalidAttr,
            static::aria_labelAttr => static::aria_labelAttr,
            static::aria_labeledbyAttr => static::aria_labeledbyAttr,
            static::aria_labelledbyAttr => static::aria_labelledbyAttr,
            static::aria_levelAttr => static::aria_levelAttr,
            static::aria_liveAttr => static::aria_liveAttr,
            static::aria_multilineAttr => static::aria_multilineAttr,
            static::aria_multiselectableAttr => static::aria_multiselectableAttr,
            static::aria_orientationAttr => static::aria_orientationAttr,
            static::aria_ownsAttr => static::aria_ownsAttr,
            static::aria_pressedAttr => static::aria_pressedAttr,
            static::aria_readonlyAttr => static::aria_readonlyAttr,
            static::aria_relevantAttr => static::aria_relevantAttr,
            static::aria_requiredAttr => static::aria_requiredAttr,
            static::aria_selectedAttr => static::aria_selectedAttr,
            static::aria_sortAttr => static::aria_sortAttr,
            static::aria_valuemaxAttr => static::aria_valuemaxAttr,
            static::aria_valueminAttr => static::aria_valueminAttr,
            static::aria_valuenowAttr => static::aria_valuenowAttr,
            static::aria_valuetextAttr => static::aria_valuetextAttr,
            static::asyncAttr => static::asyncAttr,
            static::autocompleteAttr => static::autocompleteAttr,
            static::autofocusAttr => static::autofocusAttr,
            static::autoplayAttr => static::autoplayAttr,
            static::autosaveAttr => static::autosaveAttr,
            static::axisAttr => static::axisAttr,
            static::backgroundAttr => static::backgroundAttr,
            static::behaviorAttr => static::behaviorAttr,
            static::bgcolorAttr => static::bgcolorAttr,
            static::bgpropertiesAttr => static::bgpropertiesAttr,
            static::borderAttr => static::borderAttr,
            static::bordercolorAttr => static::bordercolorAttr,
            static::cellborderAttr => static::cellborderAttr,
            static::cellpaddingAttr => static::cellpaddingAttr,
            static::cellspacingAttr => static::cellspacingAttr,
            static::challengeAttr => static::challengeAttr,
            static::charAttr => static::charAttr,
            static::charoffAttr => static::charoffAttr,
            static::charsetAttr => static::charsetAttr,
            static::checkedAttr => static::checkedAttr,
            static::citeAttr => static::citeAttr,
            static::classAttr => static::classAttr,
            static::classidAttr => static::classidAttr,
            static::clearAttr => static::clearAttr,
            static::codeAttr => static::codeAttr,
            static::codebaseAttr => static::codebaseAttr,
            static::codetypeAttr => static::codetypeAttr,
            static::colorAttr => static::colorAttr,
            static::colsAttr => static::colsAttr,
            static::colspanAttr => static::colspanAttr,
            static::compactAttr => static::compactAttr,
            static::compositeAttr => static::compositeAttr,
            static::contentAttr => static::contentAttr,
            static::contenteditableAttr => static::contenteditableAttr,
            static::controlsAttr => static::controlsAttr,
            static::coordsAttr => static::coordsAttr,
            static::dataAttr => static::dataAttr,
            static::datetimeAttr => static::datetimeAttr,
            static::declareAttr => static::declareAttr,
            static::defaultAttr => static::defaultAttr,
            static::deferAttr => static::deferAttr,
            static::dirAttr => static::dirAttr,
            static::directionAttr => static::directionAttr,
            static::disabledAttr => static::disabledAttr,
            static::draggableAttr => static::draggableAttr,
            static::enctypeAttr => static::enctypeAttr,
            static::endAttr => static::endAttr,
            static::eventAttr => static::eventAttr,
            static::expandedAttr => static::expandedAttr,
            static::faceAttr => static::faceAttr,
            static::focusedAttr => static::focusedAttr,
            static::forAttr => static::forAttr,
            static::formAttr => static::formAttr,
            static::formactionAttr => static::formactionAttr,
            static::formenctypeAttr => static::formenctypeAttr,
            static::formmethodAttr => static::formmethodAttr,
            static::formnovalidateAttr => static::formnovalidateAttr,
            static::formtargetAttr => static::formtargetAttr,
            static::frameAttr => static::frameAttr,
            static::frameborderAttr => static::frameborderAttr,
            static::headersAttr => static::headersAttr,
            static::heightAttr => static::heightAttr,
            static::hiddenAttr => static::hiddenAttr,
            static::highAttr => static::highAttr,
            static::hrefAttr => static::hrefAttr,
            static::hreflangAttr => static::hreflangAttr,
            static::hspaceAttr => static::hspaceAttr,
            static::http_equivAttr => static::http_equivAttr,
            static::idAttr => static::idAttr,
            static::incrementalAttr => static::incrementalAttr,
            static::indeterminateAttr => static::indeterminateAttr,
            static::ismapAttr => static::ismapAttr,
            static::keytypeAttr => static::keytypeAttr,
            static::kindAttr => static::kindAttr,
            static::labelAttr => static::labelAttr,
            static::langAttr => static::langAttr,
            static::languageAttr => static::languageAttr,
            static::leftmarginAttr => static::leftmarginAttr,
            static::linkAttr => static::linkAttr,
            static::listAttr => static::listAttr,
            static::longdescAttr => static::longdescAttr,
            static::loopAttr => static::loopAttr,
            static::loopendAttr => static::loopendAttr,
            static::loopstartAttr => static::loopstartAttr,
            static::lowAttr => static::lowAttr,
            static::lowsrcAttr => static::lowsrcAttr,
            static::manifestAttr => static::manifestAttr,
            static::marginheightAttr => static::marginheightAttr,
            static::marginwidthAttr => static::marginwidthAttr,
            static::maxAttr => static::maxAttr,
            static::maxlengthAttr => static::maxlengthAttr,
            static::mayscriptAttr => static::mayscriptAttr,
            static::mediaAttr => static::mediaAttr,
            static::methodAttr => static::methodAttr,
            static::minAttr => static::minAttr,
            static::multipleAttr => static::multipleAttr,
            static::nameAttr => static::nameAttr,
            static::nohrefAttr => static::nohrefAttr,
            static::noresizeAttr => static::noresizeAttr,
            static::noshadeAttr => static::noshadeAttr,
            static::novalidateAttr => static::novalidateAttr,
            static::nowrapAttr => static::nowrapAttr,
            static::objectAttr => static::objectAttr,
            static::onabortAttr => static::onabortAttr,
            static::onbeforecopyAttr => static::onbeforecopyAttr,
            static::onbeforecutAttr => static::onbeforecutAttr,
            static::onbeforeloadAttr => static::onbeforeloadAttr,
            static::onbeforepasteAttr => static::onbeforepasteAttr,
            static::onbeforeprocessAttr => static::onbeforeprocessAttr,
            static::onbeforeunloadAttr => static::onbeforeunloadAttr,
            static::onblurAttr => static::onblurAttr,
            static::oncanplayAttr => static::oncanplayAttr,
            static::oncanplaythroughAttr => static::oncanplaythroughAttr,
            static::onchangeAttr => static::onchangeAttr,
            static::onclickAttr => static::onclickAttr,
            static::oncontextmenuAttr => static::oncontextmenuAttr,
            static::oncopyAttr => static::oncopyAttr,
            static::oncutAttr => static::oncutAttr,
            static::ondblclickAttr => static::ondblclickAttr,
            static::ondragAttr => static::ondragAttr,
            static::ondragendAttr => static::ondragendAttr,
            static::ondragenterAttr => static::ondragenterAttr,
            static::ondragleaveAttr => static::ondragleaveAttr,
            static::ondragoverAttr => static::ondragoverAttr,
            static::ondragstartAttr => static::ondragstartAttr,
            static::ondropAttr => static::ondropAttr,
            static::ondurationchangeAttr => static::ondurationchangeAttr,
            static::onemptiedAttr => static::onemptiedAttr,
            static::onendedAttr => static::onendedAttr,
            static::onerrorAttr => static::onerrorAttr,
            static::onfocusAttr => static::onfocusAttr,
            static::onfocusinAttr => static::onfocusinAttr,
            static::onfocusoutAttr => static::onfocusoutAttr,
            static::onhashchangeAttr => static::onhashchangeAttr,
            static::oninputAttr => static::oninputAttr,
            static::oninvalidAttr => static::oninvalidAttr,
            static::onkeydownAttr => static::onkeydownAttr,
            static::onkeypressAttr => static::onkeypressAttr,
            static::onkeyupAttr => static::onkeyupAttr,
            static::onloadAttr => static::onloadAttr,
            static::onloadeddataAttr => static::onloadeddataAttr,
            static::onloadedmetadataAttr => static::onloadedmetadataAttr,
            static::onloadstartAttr => static::onloadstartAttr,
            static::onmousedownAttr => static::onmousedownAttr,
            static::onmousemoveAttr => static::onmousemoveAttr,
            static::onmouseoutAttr => static::onmouseoutAttr,
            static::onmouseoverAttr => static::onmouseoverAttr,
            static::onmouseupAttr => static::onmouseupAttr,
            static::onmousewheelAttr => static::onmousewheelAttr,
            static::onofflineAttr => static::onofflineAttr,
            static::ononlineAttr => static::ononlineAttr,
            static::onorientationchangeAttr => static::onorientationchangeAttr,
            static::onpagehideAttr => static::onpagehideAttr,
            static::onpageshowAttr => static::onpageshowAttr,
            static::onpasteAttr => static::onpasteAttr,
            static::onpauseAttr => static::onpauseAttr,
            static::onplayAttr => static::onplayAttr,
            static::onplayingAttr => static::onplayingAttr,
            static::onpopstateAttr => static::onpopstateAttr,
            static::onprogressAttr => static::onprogressAttr,
            static::onratechangeAttr => static::onratechangeAttr,
            static::onresetAttr => static::onresetAttr,
            static::onresizeAttr => static::onresizeAttr,
            static::onscrollAttr => static::onscrollAttr,
            static::onsearchAttr => static::onsearchAttr,
            static::onseekedAttr => static::onseekedAttr,
            static::onseekingAttr => static::onseekingAttr,
            static::onselectAttr => static::onselectAttr,
            static::onselectionchangeAttr => static::onselectionchangeAttr,
            static::onselectstartAttr => static::onselectstartAttr,
            static::onstalledAttr => static::onstalledAttr,
            static::onstorageAttr => static::onstorageAttr,
            static::onsubmitAttr => static::onsubmitAttr,
            static::onsuspendAttr => static::onsuspendAttr,
            static::ontimeupdateAttr => static::ontimeupdateAttr,
            static::ontouchcancelAttr => static::ontouchcancelAttr,
            static::ontouchendAttr => static::ontouchendAttr,
            static::ontouchmoveAttr => static::ontouchmoveAttr,
            static::ontouchstartAttr => static::ontouchstartAttr,
            static::onunloadAttr => static::onunloadAttr,
            static::onvolumechangeAttr => static::onvolumechangeAttr,
            static::onwaitingAttr => static::onwaitingAttr,
            static::onwebkitanimationendAttr => static::onwebkitanimationendAttr,
            static::onwebkitanimationiterationAttr => static::onwebkitanimationiterationAttr,
            static::onwebkitanimationstartAttr => static::onwebkitanimationstartAttr,
            static::onwebkitbeginfullscreenAttr => static::onwebkitbeginfullscreenAttr,
            static::onwebkitendfullscreenAttr => static::onwebkitendfullscreenAttr,
            static::onwebkitfullscreenchangeAttr => static::onwebkitfullscreenchangeAttr,
            static::onwebkitspeechchangeAttr => static::onwebkitspeechchangeAttr,
            static::onwebkittransitionendAttr => static::onwebkittransitionendAttr,
            static::openAttr => static::openAttr,
            static::optimumAttr => static::optimumAttr,
            static::patternAttr => static::patternAttr,
            static::pingAttr => static::pingAttr,
            static::placeholderAttr => static::placeholderAttr,
            static::playcountAttr => static::playcountAttr,
            static::pluginspageAttr => static::pluginspageAttr,
            static::pluginurlAttr => static::pluginurlAttr,
            static::posterAttr => static::posterAttr,
            static::precisionAttr => static::precisionAttr,
            static::preloadAttr => static::preloadAttr,
            static::primaryAttr => static::primaryAttr,
            static::profileAttr => static::profileAttr,
            static::progressAttr => static::progressAttr,
            static::promptAttr => static::promptAttr,
            static::readonlyAttr => static::readonlyAttr,
            static::relAttr => static::relAttr,
            static::requiredAttr => static::requiredAttr,
            static::resultsAttr => static::resultsAttr,
            static::revAttr => static::revAttr,
            static::roleAttr => static::roleAttr,
            static::rowsAttr => static::rowsAttr,
            static::rowspanAttr => static::rowspanAttr,
            static::rulesAttr => static::rulesAttr,
            static::sandboxAttr => static::sandboxAttr,
            static::schemeAttr => static::schemeAttr,
            static::scopeAttr => static::scopeAttr,
            static::scrollamountAttr => static::scrollamountAttr,
            static::scrolldelayAttr => static::scrolldelayAttr,
            static::scrollingAttr => static::scrollingAttr,
            static::selectedAttr => static::selectedAttr,
            static::shapeAttr => static::shapeAttr,
            static::sizeAttr => static::sizeAttr,
            static::sortableAttr => static::sortableAttr,
            static::sortdirectionAttr => static::sortdirectionAttr,
            static::spanAttr => static::spanAttr,
            static::spellcheckAttr => static::spellcheckAttr,
            static::srcAttr => static::srcAttr,
            static::srclangAttr => static::srclangAttr,
            static::standbyAttr => static::standbyAttr,
            static::startAttr => static::startAttr,
            static::stepAttr => static::stepAttr,
            static::styleAttr => static::styleAttr,
            static::summaryAttr => static::summaryAttr,
            static::tabindexAttr => static::tabindexAttr,
            static::tableborderAttr => static::tableborderAttr,
            static::targetAttr => static::targetAttr,
            static::textAttr => static::textAttr,
            static::titleAttr => static::titleAttr,
            static::topAttr => static::topAttr,
            static::topmarginAttr => static::topmarginAttr,
            static::truespeedAttr => static::truespeedAttr,
            static::typeAttr => static::typeAttr,
            static::usemapAttr => static::usemapAttr,
            static::valignAttr => static::valignAttr,
            static::valueAttr => static::valueAttr,
            static::valuetypeAttr => static::valuetypeAttr,
            static::versionAttr => static::versionAttr,
            static::viewsourceAttr => static::viewsourceAttr,
            static::vlinkAttr => static::vlinkAttr,
            static::vspaceAttr => static::vspaceAttr,
            static::webkitallowfullscreenAttr => static::webkitallowfullscreenAttr,
            static::webkitdirectoryAttr => static::webkitdirectoryAttr,
            static::webkitgrammarAttr => static::webkitgrammarAttr,
            static::webkitspeechAttr => static::webkitspeechAttr,
            static::widthAttr => static::widthAttr,
            static::wrapAttr => static::wrapAttr,
        );
    }

}
